-- Create fila_impressao table
create table fila_impressao (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  conteudo jsonb not null, -- Aqui vai o pedido: { mesa: 10, itens: [...] }
  status text default 'pendente', -- pendente, impresso, erro
  impresso_em timestamp with time zone
);