// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzraoioswaqmzbadosik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6cmFvaW9zd2FxbXpiYWRvc2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDg0MTQsImV4cCI6MjA2NDQ4NDQxNH0.q904kFkmb4u6Xt2ccR5g-rG0CiXrXzvVOyjX76hgAqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);